### ISSUE TITLE
输入账号密码 闪退

### ISSUE THREAD

**Issue by zachary-zhang** [zhnnnnn/ZHNCosmos#1]
- (RACSignal *)urlFormatter:(ZHNTimelineStatus *)status richTextMaxWidth:(CGFloat)richTextMaxWidth; 这个方法 应该要判断string为空否则出现闪退现象 if (!urlStruct.replaceString) break;

**Comment by zhnnnnn** [comment]
感谢~~你能登录吗？登录是用原生js直接操作webview的然后逻辑不是很完善，有时候会登录不了

**Comment by zachary-zhang** [comment]
我增加了为空判断 就可以了

**Comment by zhnnnnn** [comment]
ok~~ 感谢~~ 已修改
