### ISSUE TITLE
https://passport.weibo.cn/sso/login 授权失败

### ISSUE THREAD

**Issue by oxiangyang** [zhnnnnn/ZHNCosmos#10]
您好，https://passport.weibo.cn/sso/login 错是什么原因呢？

**Comment by zhnnnnn** [comment]
直接403了，接口用不了了应该

**Comment by oxiangyang** [comment]
> 直接403了，接口用不了了应该

发现 Cosmos 客户端这个请求是可以通的，不明白什么问题。可以修复以使用项目跑通吗?

**Comment by zhnnnnn** [comment]
我这边试了。我能登录哇~换个账号试试？
