### ISSUE TITLE
数据修复好了吗？

### ISSUE THREAD

**Issue by xiaozhouboy** [zhnnnnn/ZHNCosmos#11]

**Comment by zhnnnnn** [comment]
修不了了，微博把移动端api都封了貌似。。刚才去看了下还能用的第三方微博api用的都是网页api了。最近没精力搞了。你有兴趣可以去试试抓一下【奇点】的接口看看，我代码里模拟网页登录获取cookie的逻辑都有 `ZHNWeiBoUserCookieManager`

**Comment by zhnnnnn** [comment]
突然想起来我之前存了些本地数据的。更新了下代码，现在数据都走本地了你可以试试，不过也就只能看看主页了。。大致看看ui
