### ISSUE TITLE
登录成功 然后crash了

### ISSUE THREAD

**Issue by wunshine** [zhnnnnn/ZHNCosmos#2]
2018-01-29 15:12:02.256208+0800 ZHNCosmos[66126:2946271] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108ac412b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010d49af41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108b39245 +[NSException raise:format:] + 197
	3   Foundation                          0x00000001098956a7 -[NSRLEArray objectAtIndex:effectiveRange:] + 140
	4   Foundation                          0x0000000109894f40 -[NSConcreteMutableAttributedString replaceCharactersInRange:withString:] + 175
	5   ZHNCosmos                           0x0000000107cf6dec -[NSMutableAttributedString(YYText) yy_insertString:atIndex:] + 172
	6   ZHNCosmos                           0x00000001077c7d3c __62-[RACSignal(ZHNRichTextHelper) urlFormatter:richTextMaxWidth:]_block_invoke.274 + 604
	7   CoreFoundation                      0x0000000108a50f8f -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223
	8   ZHNCosmos                           0x00000001077c7424 __62-[RACSignal(ZHNRichTextHelper) urlFormatter:richTextMaxWidth:]_block_invoke + 4660
	9   ZHNCosmos                           0x00000001079d3920 __36-[RACStream(Operations) flattenMap:]_block_invoke_2 + 96
	10  ZHNCosmos                           0x00000001079cbd10 __29-[RACSignal(RACStream) bind:]_block_invoke.131 + 144
	11  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	12  ZHNCosmos                           0x0000000107999959 -[RACPassthroughSubscriber sendNext:] + 441
	13  ZHNCosmos                           0x00000001079cb83b __29-[RACSignal(RACStream) bind:]_block_invoke_2.104 + 75
	14  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	15  ZHNCosmos                           0x000000010799d5e1 __29-[RACReturnSignal subscribe:]_block_invoke + 81
	16  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	17  ZHNCosmos                           0x000000010799d50d -[RACReturnSignal subscribe:] + 637
	18  ZHNCosmos                           0x00000001079cfaa8 -[RACSignal(Subscription) subscribeNext:error:completed:] + 1512
	19  ZHNCosmos                           0x00000001079cb6e3 __29-[RACSignal(RACStream) bind:]_block_invoke.94 + 755
	20  ZHNCosmos                           0x00000001079cbd45 __29-[RACSignal(RACStream) bind:]_block_invoke.131 + 197
	21  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	22  ZHNCosmos                           0x0000000107999959 -[RACPassthroughSubscriber sendNext:] + 441
	23  ZHNCosmos                           0x00000001079cb83b __29-[RACSignal(RACStream) bind:]_block_invoke_2.104 + 75
	24  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	25  ZHNCosmos                           0x000000010799d5e1 __29-[RACReturnSignal subscribe:]_block_invoke + 81
	26  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	27  ZHNCosmos                           0x000000010799d50d -[RACReturnSignal subscribe:] + 637
	28  ZHNCosmos                           0x00000001079cfaa8 -[RACSignal(Subscription) subscribeNext:error:completed:] + 1512
	29  ZHNCosmos                           0x00000001079cb6e3 __29-[RACSignal(RACStream) bind:]_block_invoke.94 + 755
	30  ZHNCosmos                           0x00000001079cbd45 __29-[RACSignal(RACStream) bind:]_block_invoke.131 + 197
	31  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	32  ZHNCosmos                           0x0000000107999959 -[RACPassthroughSubscriber sendNext:] + 441
	33  ZHNCosmos                           0x00000001079cb83b __29-[RACSignal(RACStream) bind:]_block_invoke_2.104 + 75
	34  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	35  ZHNCosmos                           0x000000010799d5e1 __29-[RACReturnSignal subscribe:]_block_invoke + 81
	36  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	37  ZHNCosmos                           0x000000010799d50d -[RACReturnSignal subscribe:] + 637
	38  ZHNCosmos                           0x00000001079cfaa8 -[RACSignal(Subscription) subscribeNext:error:completed:] + 1512
	39  ZHNCosmos                           0x00000001079cb6e3 __29-[RACSignal(RACStream) bind:]_block_invoke.94 + 755
	40  ZHNCosmos                           0x00000001079cbd45 __29-[RACSignal(RACStream) bind:]_block_invoke.131 + 197
	41  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	42  ZHNCosmos                           0x0000000107999959 -[RACPassthroughSubscriber sendNext:] + 441
	43  ZHNCosmos                           0x00000001077de8ff __54-[RACSignal(statusMapping) formatterRichTextMaxWidth:]_block_invoke.324 + 223
	44  ZHNCosmos                           0x000000010798ea2a __30-[RACDynamicSignal subscribe:]_block_invoke + 74
	45  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	46  ZHNCosmos                           0x000000010798e8fa -[RACDynamicSignal subscribe:] + 874
	47  ZHNCosmos                           0x00000001079cfaa8 -[RACSignal(Subscription) subscribeNext:error:completed:] + 1512
	48  ZHNCosmos                           0x00000001079caef3 __29-[RACSignal(RACStream) bind:]_block_invoke + 1331
	49  ZHNCosmos                           0x000000010798ea2a __30-[RACDynamicSignal subscribe:]_block_invoke + 74
	50  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	51  ZHNCosmos                           0x000000010798e8fa -[RACDynamicSignal subscribe:] + 874
	52  ZHNCosmos                           0x00000001079cfaa8 -[RACSignal(Subscription) subscribeNext:error:completed:] + 1512
	53  ZHNCosmos                           0x00000001079caef3 __29-[RACSignal(RACStream) bind:]_block_invoke + 1331
	54  ZHNCosmos                           0x000000010798ea2a __30-[RACDynamicSignal subscribe:]_block_invoke + 74
	55  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	56  ZHNCosmos                           0x000000010798e8fa -[RACDynamicSignal subscribe:] + 874
	57  ZHNCosmos                           0x00000001079cfaa8 -[RACSignal(Subscription) subscribeNext:error:completed:] + 1512
	58  ZHNCosmos                           0x00000001079caef3 __29-[RACSignal(RACStream) bind:]_block_invoke + 1331
	59  ZHNCosmos                           0x000000010798ea2a __30-[RACDynamicSignal subscribe:]_block_invoke + 74
	60  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	61  ZHNCosmos                           0x000000010798e8fa -[RACDynamicSignal subscribe:] + 874
	62  ZHNCosmos                           0x00000001079cfaa8 -[RACSignal(Subscription) subscribeNext:error:completed:] + 1512
	63  ZHNCosmos                           0x00000001079caef3 __29-[RACSignal(RACStream) bind:]_block_invoke + 1331
	64  ZHNCosmos                           0x000000010798ea2a __30-[RACDynamicSignal subscribe:]_block_invoke + 74
	65  ZHNCosmos                           0x00000001079dd08c -[RACSubscriptionScheduler schedule:] + 604
	66  ZHNCosmos                           0x000000010798e8fa -[RACDynamicSignal subscribe:] + 874
	67  ZHNCosmos                           0x00000001079cf02a -[RACSignal(Subscription) subscribeNext:] + 522
	68  ZHNCosmos                           0x00000001077de4c7 __54-[RACSignal(statusMapping) formatterRichTextMaxWidth:]_block_invoke_2 + 1895
	69  CoreFoundation                      0x0000000108a50f8f -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223
	70  ZHNCosmos                           0x00000001077ddd15 __54-[RACSignal(statusMapping) formatterRichTextMaxWidth:]_block_invoke + 133
	71  ZHNCosmos                           0x00000001079d3920 __36-[RACStream(Operations) flattenMap:]_block_invoke_2 + 96
	72  ZHNCosmos                           0x00000001079cbd10 __29-[RACSignal(RACStream) bind:]_block_invoke.131 + 144
	73  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	74  ZHNCosmos                           0x0000000107999959 -[RACPassthroughSubscriber sendNext:] + 441
	75  ZHNCosmos                           0x00000001079cb83b __29-[RACSignal(RACStream) bind:]_block_invoke_2.104 + 75
	76  ZHNCosmos                           0x00000001079dc16c -[RACSubscriber sendNext:] + 236
	77  ZHNCosmos                           0x000000010799d5e1 __29-[RACReturnSignal subscribe:]_block_invoke + 81
	78  ZHNCosmos                           0x000000010799f73e -[RACScheduler performAsCurrentScheduler:] + 638
	79  ZHNCosmos                           0x000000010799aa64 __30-[RACQueueScheduler schedule:]_block_invoke + 84
	80  libdispatch.dylib                   0x000000010ff692f7 _dispatch_call_block_and_release + 12
	81  libdispatch.dylib                   0x000000010ff6a33d _dispatch_client_callout + 8
	82  libdispatch.dylib                   0x000000010ff72855 _dispatch_queue_serial_drain + 1162
	83  libdispatch.dylib                   0x000000010ff731ea _dispatch_queue_invoke + 336
	84  libdispatch.dylib                   0x000000010ff6ef7c _dispatch_queue_override_invoke + 733
	85  libdispatch.dylib                   0x000000010ff76102 _dispatch_root_queue_drain + 772
	86  libdispatch.dylib                   0x000000010ff75da0 _dispatch_worker_thread3 + 132
	87  libsystem_pthread.dylib             0x00000001104351ca _pthread_wqthread + 1387
	88  libsystem_pthread.dylib             0x0000000110434c4d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by zachary-zhang** [comment]
(RACSignal *)urlFormatter:(ZHNTimelineStatus *)status richTextMaxWidth:(CGFloat)richTextMaxWidth; 这个方法 应该要判断string为空否   if (!urlStruct.replaceString) break; 就可以了

**Comment by zhnnnnn** [comment]
感谢反馈~已修改~

**Comment by wunshine** [comment]
if (rect.size.height > fontWH * 2) {
                [attributedString yy_insertString:@"\n" atIndex:urlRange.location];
                offset++;
            }else if (rect.origin.x + rect.size.width >= w - 5) {// 5 for padding
                [attributedString yy_insertString:@"\n" atIndex:urlRange.location];
                offset++;
            }

[lldb]$po attributedString.string.length
174
[lldb]$po urlRange.location
179

越界了还是要挂~

**Comment by wunshine** [comment]
[attributedString yy_insertString:@"\n" atIndex:urlRange.location-5];
这样就可以了

**Comment by zhnnnnn** [comment]
自己的账号没出过问题= =样本有点小，我还没办法具体定位问题。。微博链接显示这里比较蛋疼，设置了boder可能会换行，所以判断boder换行了的话插了个\n在最前面，不清楚你修改以后插入的问题对不对，界面显示会不会出问题

**Comment by wunshine** [comment]
界面显示暂时没发现问题
