### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by huainanzi** [zhnnnnn/ZHNCosmos#3]
一直处于加载状态，登录不了
打印这个[BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
2018-01-29 16:36:50.947410+0800 ZHNCosmos[19594:593511] [BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert

**Comment by zhnnnnn** [comment]
可以进ZHNCosmosUserManager里看看能走到哪一步？然后可以切换网络试试，因为这个登录是走微博的认证授权的，微博的认证授权是网页的，这里只是屏蔽了网页。

**Comment by huainanzi** [comment]
![2018-01-30 9 49 28](https://user-images.githubusercontent.com/17873544/35543994-fd006a38-05a2-11e8-8186-c645fb0f80e4.png)
登录这个位置的判断不成立

**Comment by zhnnnnn** [comment]
它会重定向的。登录的逻辑是你原生输入账号密码，然后webview打开https://passport.weibo.cn/signin/login?client_id=2323547071&redirect_uri=http://oauth.weico.cc&display=sdk&action=login&offcialMobile=true&rf=1&version=003143000&sso_type=1&scope=direct_messages_write,direct_messages_read,friendships_groups_read,friendships_groups_write 然后用js把账号密码填到webview上，然后js去点击webview的登录按钮，然后拦截重定向链接拿到数据。。。所以如果你走不到拦截逻辑情况可能是
1.账号密码错了
2.网络问题，webview加载最开始的链接一直没加载完
 
试试真机然后用4g试试
