### ISSUE TITLE
完全登录不了

### ISSUE THREAD

**Issue by JQHee** [zhnnnnn/ZHNCosmos#4]

**Comment by zhnnnnn** [comment]
登录的逻辑是你原生输入账号密码，然后webview打开https://passport.weibo.cn/signin/login?client_id=2323547071&redirect_uri=http://oauth.weico.cc&display=sdk&action=login&offcialMobile=true&rf=1&version=003143000&sso_type=1&scope=direct_messages_write,direct_messages_read,friendships_groups_read,friendships_groups_write 然后用js把账号密码填到webview上，然后js去点击webview的登录按钮，然后拦截重定向链接拿到数据。。。所以登录不成功一般是
1.账号密码错了
2.网络问题，webview加载最开始的链接一直没加载完

试试真机切换网络试试，我自己试的时候也是偶尔会登不上

**Comment by JQHee** [comment]
webView url -- https://passport.weibo.cn/signin/login?client_id=2323547071&redirect_uri=http://oauth.weico.cc&display=sdk&action=login&offcialMobile=true&rf=1&version=003143000&sso_type=1&scope=direct_messages_write,direct_messages_read,friendships_groups_read,friendships_groups_write   走到这里的时候就一直在加载了

**Comment by zhnnnnn** [comment]
我看看，这个微博授权获取token是走野路子的。。有可能是接口挂了

**Comment by zhnnnnn** [comment]
我看看，这个微博授权获取token是走野路子的。。有可能是接口挂了

**Comment by JQHee** [comment]
应该是连接用不了吧，浏览器都打不开

**Comment by zhnnnnn** [comment]
我试了用应该还能用，获取客户端的token逻辑还是通的。。。但是模拟pc登录微博获取网页cookie的接口挂了貌似。。。。你在重新试试登录，你让它一直转圈圈，过好一会会显示失败，但是你刷新一下应该还是能刷到数据

**Comment by zhnnnnn** [comment]
好像可以了，你在试试。。。。现在的moke之类的第三方微博真是刀口舔血啊= =

**Comment by zhnnnnn** [comment]
你可以在试试，我这边又试了一遍貌似是可以了。。。。。。。第三方微博的接口都不是太稳定的，不过你登录进去就好了
