### ISSUE TITLE
首页下拉刷新控件动画有问题 

### ISSUE THREAD

**Issue by zachary-zhang** [zhnnnnn/ZHNCosmos#6]
![wechatimg4](https://user-images.githubusercontent.com/9391764/35761654-1367bf26-08c6-11e8-9a32-79c6a47957ee.png)
没有新数据的情况你没考虑

**Comment by zhnnnnn** [comment]
yeap～～应该是没数据直接return了，感谢～有空我改下

**Comment by zhnnnnn** [comment]
已修改~
