### ISSUE TITLE
第一次用，登录不了

### ISSUE THREAD

**Issue by wonderffee** [zhnnnnn/ZHNCosmos#8]
填完用户名和密码后点登录进度条一直转，抓包能看到有提示：你所访问的站点在微博认证失败，错误号：21322
根据 https://blog.csdn.net/xjh093/article/details/53588571 ，应该是授权回调页的url改变了吧，因为用的第三方的授权这个是不是没办法了？
看了一下Cosmos slack群里的最近发言，好像Cosmos上周也出现过类似的问题

**Comment by zhnnnnn** [comment]
嗯嗯，cosmos刀口舔血的，用的是weico的接口，现在好像用不了了。。。等cosmos大佬更新吧，我再把登录逻辑修复一下。

**Comment by wonderffee** [comment]
不过Cosmos已登录用户似乎不影响

**Comment by zhnnnnn** [comment]
cosmos里的登录逻辑是先尝试高级权限的，如果高级权限的不行就用低级权限的。它现在的高级权限的也用不了了。。我这里只实现了了一个高级权限的逻辑。你有兴趣可以去尝试一下改一下ZHNCosmosUserManager替换成低级权限的逻辑。

**Comment by zhnnnnn** [comment]
hi，登录问题已经修复
